import os
import numpy as np

BOX_Z_HALF = 12.5      # Angstrom, half-height of vacuum region
box_x = box_z = 70     # Angstrom, extent of x and z axis


def write_data(path: str, atoms_mtxyz: np.ndarray) -> None:
    """
    Write a LAMMPS .data file for a single-element (carbon) system, using atom_style molecular.

    Args:
        path (str): output file path
        atoms_mtxyz (np.ndarray): array from geometry.assemble_graphene(), columns [molecule_id, atom_type, x, y, z]
    """

    os.makedirs(os.path.dirname(path), exist_ok=True)
    n_atoms = atoms_mtxyz.shape[0]

    x_center = (atoms_mtxyz[:, 2].min() + atoms_mtxyz[:, 2].max()) / 2
    z_center = (atoms_mtxyz[:, 4].min() + atoms_mtxyz[:, 4].max()) / 2
    xlo, xhi = x_center - box_x / 2, x_center + box_x / 2
    ylo, yhi = -BOX_Z_HALF, BOX_Z_HALF
    zlo, zhi = z_center - box_z / 2, z_center + box_z / 2


    with open(path, 'w') as f:
        f.write('# graphene sheet, generated by graphene_defect_ml\n\n')
        f.write(f'{n_atoms} atoms\n')
        f.write('1 atom types\n\n')
        f.write(f'{xlo:.5f} {xhi:.5f} xlo xhi\n')
        f.write(f'{ylo:.5f} {yhi:.5f} ylo yhi\n')
        f.write(f'{zlo:.5f} {zhi:.5f} zlo zhi\n\n')
        f.write('Masses\n\n')
        f.write('1 12.0107\n\n')
        f.write('Atoms # molecular\n\n')

        for i in range(n_atoms):
            mol_id    = int(atoms_mtxyz[i, 0])
            atom_type = int(atoms_mtxyz[i, 1])
            x, y, z   = atoms_mtxyz[i, 2], atoms_mtxyz[i, 3], atoms_mtxyz[i, 4]
            f.write(f"{i + 1} {mol_id} {atom_type} {x:.5f} {y:.5f} {z:.5f}\n")



def write_in(path: str, data_filename: str, airebo_filename: str, seed: int = 12345,
            ensemble: str = 'nvt', relax_steps: int = 10000, vibrate_steps: int = 30000,
            relax_damp: float = 0.1, vibrate_damp: float = 0.1) -> None:
    """
    Write the LAMMPS .in script for the thermal-vibration protocol
        1. NVT relax at 300 K for relax_steps
        2. Thermostatted (NVT or NPT) vibration at 300 K for vibrate_steps
        3. Dump per-atom out-of-plane (y) displacement at 20 THz
    Time step = 1 fs, AIREBO potential (modified rcmin_CC).
 
    Args:
        path (str)             : output .in file path
        data_filename (str)    : name of the .data file (same directory)
        airebo_filename (str)  : name of the (modified) AIREBO potential file (same directory)
        seed (int, optional)   : RNG seed for initial velocities. Defaults to 12345.
        ensemble (str)         : 'nvt' or 'npt' for the vibration stage. Defaults to 'nvt'.
        relax_steps (int)      : Stage-1 NVT relax duration, in 1 fs steps. Defaults to 10000 (10 ps).
        vibrate_steps (int)    : Stage-2 vibration duration, in 1 fs steps. Defaults to 30000 (30 ps).
        relax_damp (float)     : Nose-Hoover temperature damping (ps) for the Stage-1 relax fix. Defaults to 0.1.
        vibrate_damp (float)   : Nose-Hoover temperature damping (ps) for the Stage-2 vibrate fix. Defaults to 0.1.
    """

    os.makedirs(os.path.dirname(path), exist_ok=True)

    # 20 THz sampling -> dump every N steps, N = 1 / (20e12 * 1e-15) = 50
    dump_every = 50

    if ensemble not in ('nvt', 'npt'):
        raise ValueError(f"ensemble must be 'nvt' or 'npt', got {ensemble}")

    vibrate_fix_name = 'nvt_vibrate' if ensemble == 'nvt' else 'npt_vibrate'
    
    with open(path, 'w') as f:
        f.write('# graphene thermal vibration run, generated by graphene_defect_ml\n\n')
        f.write('units metal\n')
        f.write('dimension 3\n')
        f.write('boundary p f p\n')
        f.write('atom_style molecular\n')
        f.write(f'read_data {data_filename}\n\n')

        f.write('group free molecule 1\n')
        f.write('group fixed molecule 2\n\n')

        f.write('pair_style airebo 2.0\n')
        f.write(f'pair_coeff * * {airebo_filename} C\n\n')

        f.write(f'velocity free create 300.0 {seed} mom yes rot yes dist gaussian\n')
        f.write('velocity fixed set 0.0 0.0 0.0\n\n')

        f.write('fix freeze fixed setforce 0.0 0.0 0.0\n\n')

        f.write('compute freetemp free temp\n\n')

        f.write('timestep 0.001\n')      # metal units use ps; 0.001 ps = 1 fs
        f.write('thermo 1000\n')
        f.write('thermo_style custom step c_freetemp pe etotal press\n\n')

        f.write(f'#==== Stage 1: NVT relax, {relax_steps} steps ====\n')
        f.write('dump relax_full all custom 50 relax_structure.lammpstrj id x y z\n')
        f.write('dump_modify relax_full sort id\n')
        f.write(f'fix nvt_relax free nvt temp 300.0 300.0 {relax_damp}\n')
        f.write(f'run {relax_steps}\n')
        f.write('unfix nvt_relax\n')
        f.write('undump relax_full\n\n')

        f.write(f'#=== Stage 2: {ensemble.upper()} vibrate, {vibrate_steps} steps, dump out-of-plane displacement ====\n')
        f.write('compute ydisp free displace/atom\n')
        f.write(f'dump vib free custom {dump_every} vibration.lammpstrj id x y z c_ydisp[2]\n')
        f.write('dump_modify vib sort id\n')
        f.write(f'dump full_struct all custom {dump_every} full_structure.lammpstrj id x y z\n')
        f.write('dump_modify full_struct sort id\n')

        if ensemble == 'nvt':
            f.write(f'fix nvt_vibrate free nvt temp 300.0 300.0 {vibrate_damp}\n')
        else:
            f.write(f'fix {vibrate_fix_name} free npt temp 300.0 300.0 {vibrate_damp} x 0.0 0.0 1.0 z 0.0 0.0 1.0\n')

        f.write('run 30000\n')
        f.write(f'unfix {vibrate_fix_name}\n')